### PR TITLE
placeholder warning

### LINKED ISSUE #2579: React Warning: Received `false` for a non-boolean attribute `placeholder`.
**Describe the bug**

We are seeing the following warning printed out on console under dev mode:

image

#### To Reproduce

Run web-client under dev mode via yarn dev
Go the Add Dataset Page
Check the output from console

#### Expected behavior

No warning shown in the screenshot above should be produced.

### PR DESCRIPTION
**Pull request by sajidanower23**
### What this PR does

Fixes #2579 

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

File: magda-web-client/src/Components/Dataset/Add/DatasetAddMetadataPage.tsx [hunk 1]
```diff
@@ -256,7 +256,7 @@ class NewDataset extends React.Component<Props, State> {
                     <div>
                         <MultilineTextEditor
                             value={datasetPublishing.notesToApprover}
-                            placerHolder="Enter additional notes"
+                            placeHolder="Enter additional notes"
```
Comment (t83714) [inline magda-web-client/src/Components/Dataset/Add/DatasetAddMetadataPage.tsx]: @sajidanower23 
Good pickup on the typo~ 👍 
Since you're already here, could you please make the spelling more consistent with actual DOM element property name?
i.e. Change it all `placeHolder` to `placeholder`

Comment (sajidanower23) [reply magda-web-client/src/Components/Dataset/Add/DatasetAddMetadataPage.tsx]: Sure thing. Done.

File: magda-web-client/src/Components/Dataset/Add/Pages/DetailsAndContents/index.tsx [hunk 2]
```diff
@@ -75,8 +75,9 @@ export default function DatasetAddAccessAndUsePage(props: Props) {
                             value={dataset.title}
                             onChange={editDataset("title")}
                             editor={textEditorEx({
-                                placeholder:
-                                    !dataset.title && "Enter dataset title",
+                                placeholder: dataset.title
```
Comment (t83714) [inline magda-web-client/src/Components/Dataset/Add/Pages/DetailsAndContents/index.tsx]: @sajidanower23 
Had another test and it seems now placeholder won't be shown anymore.
Seems the logic here should be reversed

Comment (sajidanower23) [reply magda-web-client/src/Components/Dataset/Add/Pages/DetailsAndContents/index.tsx]: Good catch @t83714 . Switched the logic around. Should work now.
