### PR TITLE
Issue/1033 Registry now will retry failed webhook targets

### LINKED ISSUE #1033: Failed webhook targets should attempt to be revived
### Problem description
Right now, if a POST to a webhook fails too many times, the registry sets that webhook to inactive, then when the webhook recipient (sleuther, indexer) gets restarted it'll resume itself.

_However_ it doesn't always go this way... if the pod listening for the webhooks isn't stopped at the time the webhook gets cancelled, it won't re-register itself because it won't restart.

This usually works out just because kubernetes restarts things so often, but we can't rely upon it - datasets are slipping through the cracks and not getting indexed for a week after they're published on a source.

So we need to fix this somehow - either the registry api needs to periodically retry inactive hook targets, or hook targets need to periodically re-register themselves - perhaps when they spend a few hours without any new hooks?

If it's done on the registry side it might be a problem, because we've just got a single "inactive" column which conflates hooks that have hit an error with ones that are manually deactivated. On the other hand I don't know of any hooks we've intentionally deactivated, so we could probably just rename that one and add another column for manually disabled hooks.

### PR DESCRIPTION
**Pull request by t83714**
### What this PR does

Fixes #1033 
- Added two new columns to webhooks table
- Implement the retry logic in `WebHookActor` using scheduled message
  - default initial checking time interval is 10 mins
  - with backoff of `2 ^ retryCount * retryInterval`
- Make sure retryCount & lastRetryTime is reset by registry upon successful contact to webhooks
- Added two test cases (one in WebHookActor the other one in WebHookProcessingSpec )

P.S. Tried newer version swagger-codegen (tried Master branch 2.x version). It seems it still won't generate typescript code with optional field. Thus, didn't update swagger-codegen.

### Dev Site Test Info:

I think it might be easier if test it in the following way:
- Modify webhook record (i.e. the one for `sleuther-linked-data-rating`) and:
  - set `active` & `enabled` to false  
  - set `lastevent` to a lower number  
  - Set `lastRetryTime` to null
  - Set `retryCount` to 0
- Then, restart `Registry API` Pod. `sleuther-linked-data-rating` hook should not run and you should see the folloing in `registry` log:
```
[INFO] [08/23/2018 00:03:00.331] [registry-api-akka.actor.default-dispatcher-3] [akka://registry-api/user/WebHookActor] Start to retry all inactive webhooks...
[INFO] [08/23/2018 00:03:00.354] [registry-api-akka.actor.default-dispatcher-3] [akka://registry-api/user/WebHookActor] Completed retry all inactive webhooks: No inactive webhook need to be restarted...
```
- Update webhook record and set `enabled` field to `true` (but still leave `active` to `false`).
- Wait 10 mins
- You should see the followings:
```
[INFO] [08/23/2018 00:13:00.321] [registry-api-akka.actor.default-dispatcher-8] [akka://registry-api/user/WebHookActor] Start to retry all inactive webhooks...
[INFO] [08/23/2018 00:13:00.354] [registry-api-akka.actor.default-dispatcher-8] [akka://registry-api/user/WebHookActor] Invalidate Webhook Cache for retry 1 inactive hooks...
[INFO] [08/23/2018 00:13:00.361] [registry-api-akka.actor.default-dispatcher-5] [akka://registry-api/user/WebHookActor] Creating new web hook actor for sleuther-linked-data-rating.
[INFO] [08/23/2018 00:13:00.362] [registry-api-akka.actor.default-dispatcher-8] [akka://registry-api/user/WebHookActor] Sending Process message...
[INFO] [08/23/2018 00:13:00.362] [registry-api-akka.actor.default-dispatcher-8] [akka://registry-api/user/WebHookActor] Completed retry all inactive webhooks.
[INFO] [08/23/2018 00:13:02.710] [registry-api-akka.actor.default-dispatcher-10] [akka://registry-api/user/WebHookActor/WebHookActor-sleuther-linked-data-rating-98746e98-51d2-4c8d-bdfb-e7c07739f39a] WebHook sleuther-linked-data-rating Processing Some(900000)-Some(900473): STARTING
[INFO] [08/23/2018 00:13:03.361] [registry-api-akka.actor.default-dispatcher-10] [akka://registry-api/user/WebHookActor/WebHookActor-sleuther-linked-data-rating-98746e98-51d2-4c8d-bdfb-e7c07739f39a] WebHook sleuther-linked-data-rating Processing Some(900000)-Some(900473): DELIVERED
```
- You also can verfify whether registry has attempted to retry hooks or not by look at database columns:
  - lastRetryTime
  - retryCount

### Checklist

-   [x] There are unit tests to verify my changes are correct
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)
-   [x] I've assigned this PR to someone (if you don't know who to assign it to, pick @AlexGilleran)

### CODE REVIEW

File: magda-registry-api/src/main/scala/au/csiro/data61/magda/registry/WebHookActor.scala [hunk 1]
```diff
@@ -80,8 +84,14 @@ object WebHookActor {
 
     setup
 
+    scheduler.schedule(500 milliseconds, webHooksRetryInterval milliseconds, self, RetryInactiveHooks)
```
Comment (AlexGilleran) [inline magda-registry-api/src/main/scala/au/csiro/data61/magda/registry/WebHookActor.scala]: Is this checking every 500 milliseconds? Seems a bit excessive, maybe every 10 seconds or so?

Comment (t83714) [reply magda-registry-api/src/main/scala/au/csiro/data61/magda/registry/WebHookActor.scala]: The first parameter (500 mil) is the initial delay (put a non zero value just in case).
The second parameter: webHooksRetryInterval milliseconds is the Interval.
Here is the docs:
https://doc.akka.io/docs/akka/2.4.18/scala/scheduler.html
By the way, it seems Akka 2.5 got a lot of new feature around timer & scheduler.
We probably want to upgrade to a newer version one day~

**Comment by t83714** [comment]
@AlexGilleran 
Sounds a good idea~
Will add a new `enable` column for user control.
Let me know if you have a better column name~ 😄

File: magda-registry-api/src/main/scala/au/csiro/data61/magda/registry/WebHookActor.scala (hunk 1 above)
Comment (AlexGilleran) [reply magda-registry-api/src/main/scala/au/csiro/data61/magda/registry/WebHookActor.scala]: Ah ok, sounds good 👍

**Comment by t83714** [comment]
@AlexGilleran 
This should be ready to look at again~
Also added 3 test cases for the new `enabled` fields

**Comment by t83714** [comment]
Some info on changes:
- Now registry will send process message upon webhook invalidation (as part of `retry` process)
- More logs during the `retry`
- Adjusted test case logic so it will test whether Sluether will get at least one payload after the webhook re-creation

**Comment by AlexGilleran** [comment]
I'm still not seeing it work. What I did was delete the linked-data-rating sleuther, set it to enabled=false, then set it to enabled=true again and did a POST to the registry to invalidate the cache.

What appears to have happened is that it retries the hook, sets it to active=true, tries to post a webhook to it, that fails but the hook remains active, then 10 minutes later it says "No inactive hook needs to be restarted", presumably because it's set to active even though it's not processing.

 This is the log:
```
[INFO] [08/23/2018 01:01:00.478] [registry-api-akka.actor.default-dispatcher-13] [akka://registry-api/user/WebHookActor/WebHookActor-sleuther-linked-data-rating-98746e98-51d2-4c8d-bdfb-e7c07739f39a] WebHook sleuther-linked-data-rating Processing Some(1539487)-Some(1539895): STARTING
[INFO] [08/23/2018 01:01:01.527] [registry-api-akka.actor.default-dispatcher-15] [akka://registry-api/user/WebHookActor/WebHookActor-sleuther-linked-data-rating-98746e98-51d2-4c8d-bdfb-e7c07739f39a] WebHook sleuther-linked-data-rating Processing Some(1539487)-Some(1539895): DELIVERED
[INFO] [08/23/2018 01:01:03.441] [registry-api-akka.actor.default-dispatcher-15] [akka://registry-api/user/WebHookActor/WebHookActor-sleuther-linked-data-rating-98746e98-51d2-4c8d-bdfb-e7c07739f39a] WebHook sleuther-linked-data-rating Processing Some(1539895)-Some(1540309): STARTING
[ERROR] [08/23/2018 01:01:13.546] [registry-api-akka.actor.default-dispatcher-14] [akka://registry-api/user/WebHookActor/WebHookActor-sleuther-linked-data-rating-98746e98-51d2-4c8d-bdfb-e7c07739f39a] WebHook sleuther-linked-data-rating Processing Some(1539895)-Some(1540309): FAILED (akka.stream.StreamTcpException)
[INFO] [08/23/2018 01:03:00.330] [registry-api-akka.actor.default-dispatcher-9] [akka://registry-api/user/WebHookActor] Start to retry all inactive webhooks...
[INFO] [08/23/2018 01:03:00.333] [registry-api-akka.actor.default-dispatcher-9] [akka://registry-api/user/WebHookActor] Completed retry all inactive webhooks: No inactive webhook need to be restarted...
[INFO] [08/23/2018 01:04:53.926] [registry-api-akka.actor.default-dispatcher-24] [akka://registry-api/user/WebHookActor] Invalidated webhook cache
[INFO] [08/23/2018 01:04:58.886] [registry-api-akka.actor.default-dispatcher-24] [akka://registry-api/user/WebHookActor] Invalidated webhook cache
[INFO] [08/23/2018 01:05:29.203] [registry-api-akka.actor.default-dispatcher-22] [akka://registry-api/user/WebHookActor] Invalidated webhook cache
[INFO] [08/23/2018 01:13:00.332] [registry-api-akka.actor.default-dispatcher-25] [akka://registry-api/user/WebHookActor] Start to retry all inactive webhooks...
[INFO] [08/23/2018 01:13:00.369] [registry-api-akka.actor.default-dispatcher-25] [akka://registry-api/user/WebHookActor] Invalidate Webhook Cache for retry 1 inactive hooks...
[INFO] [08/23/2018 01:13:00.372] [registry-api-akka.actor.default-dispatcher-36] [akka://registry-api/user/WebHookActor] Creating new web hook actor for sleuther-linked-data-rating.
[INFO] [08/23/2018 01:13:00.373] [registry-api-akka.actor.default-dispatcher-25] [akka://registry-api/user/WebHookActor] Sending Process message...
[INFO] [08/23/2018 01:13:00.373] [registry-api-akka.actor.default-dispatcher-25] [akka://registry-api/user/WebHookActor] Completed retry all inactive webhooks.
[INFO] [08/23/2018 01:13:02.459] [registry-api-akka.actor.default-dispatcher-25] [akka://registry-api/user/WebHookActor/WebHookActor-sleuther-linked-data-rating-1ebeacbe-07f8-4b1e-9fa6-a24979bb0483] WebHook sleuther-linked-data-rating Processing Some(1539895)-Some(1540309): STARTING
[INFO] [08/23/2018 01:13:06.238] [registry-api-akka.actor.default-dispatcher-39] [akka://registry-api/user/WebHookActor/WebHookActor-indexer-774a3253-5cb3-4dd7-9179-2e95c9850b0b] WebHook indexer: Up to date at event Some(9933837)
[ERROR] [08/23/2018 01:13:12.583] [registry-api-akka.actor.default-dispatcher-39] [akka://registry-api/user/WebHookActor/WebHookActor-sleuther-linked-data-rating-1ebeacbe-07f8-4b1e-9fa6-a24979bb0483] WebHook sleuther-linked-data-rating Processing Some(1539895)-Some(1540309): FAILED (akka.stream.StreamTcpException)
[INFO] [08/23/2018 01:23:00.321] [registry-api-akka.actor.default-dispatcher-38] [akka://registry-api/user/WebHookActor] Start to retry all inactive webhooks...
[INFO] [08/23/2018 01:23:00.324] [registry-api-akka.actor.default-dispatcher-38] [akka://registry-api/user/WebHookActor] Completed retry all inactive webhooks: No inactive webhook need to be restarted...
```

**Comment by t83714** [comment]
@AlexGilleran 
Had a test on dev test. 
It seems working fine now~ 🎉 
Please help to have another test if you have the chance~
Just in case I always tested it in the same patterns...
By the way, you now can get hook actior running status from GetHooks API --- Could be handy when try to figure out what happened.

**Comment by AlexGilleran** [comment]
Works great 🎉
