### PR TITLE
Issue/2414 Fixed: drop a folder to Add dataset file drop area will break the UI

### LINKED ISSUE #2414: File Drop Area allows folder drop but cannot process it properly
**Describe the bug**

The File Drop Area on the add dataset page currently allows users to drag & drop a folder/directory. However, this leads to incorrect program behaviour (breaks the UI as next & save buttons are disappeared) & errors. See screenshot:

image
 
We probably want to either disable the `Folder / Directory drop` or make it process correctly.

### PR DESCRIPTION
**Pull request by t83714**
### What this PR does

Fixes #2414 

This PR will auto skip any dir items you dropped to file drop area without breaking the UI.

### Checklist

-   [x] unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

File: magda-web-client/src/Components/Dataset/Add/DatasetAddFilesPage.tsx [hunk 1]
```diff
@@ -49,10 +49,29 @@ class DatasetAddFilesPage extends React.Component<
         });
     }
 
-    addFiles = async (fileList: FileList) => {
+    private isDirItem(idx: number, event: any) {
+        try {
+            if (!event) return false;
+            // --- access web browser API to test whether it's a directory
+            const rawEntry = event.dataTransfer.items[idx].webkitGetAsEntry();
```
Comment (AlexGilleran) [inline magda-web-client/src/Components/Dataset/Add/DatasetAddFilesPage.tsx]: should this be `getAsEntry() || webkitGetAsEntry()` for future proofing? https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry

Comment (t83714) [reply magda-web-client/src/Components/Dataset/Add/DatasetAddFilesPage.tsx]: 👍 Updated accordingly
