### PR TITLE
Fixed: if featureFlags are not set, edit buttons are always shown on dataset page

### LINKED ISSUE #2671: User shouldn't see edit buttons on view dataset page unless login as admin
**Describe the bug**
User shouldn't see edit buttons on view dataset page unless login as admin.

see screehshot below, without login the button is shown up:

image

### PR DESCRIPTION
**Pull request by t83714**
### What this PR does

Fixes #2671 
Cause:
- Default value for `featureFlags` in helm chart is `{}`
- If `featureFlags` is not set when deployed, `config.featureFlags.cataloguing` will be `undefined`
- `hasEditPermissions` property (`DatasetPage`) is calculated as:
```js
const hasEditPermissions =
        config.featureFlags.cataloguing &&
        state.userManagement &&
        state.userManagement.user &&
        state.userManagement.user.isAdmin;
```

Its value will **always** be `undefined` rather than `false`

- The way of `ToggleEditor` figure out whether the edit mode is enable or not was:
```js
enabled = enabled === undefined || enabled;
```
This make it `true` when `enabled` = `undefined`

### Checklist

-   [x] unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

File: magda-web-client/src/Components/Editing/ToggleEditor.tsx [hunk 1]
```diff
@@ -56,7 +56,7 @@ export class ToggleEditor<V> extends React.Component<ToggleEditorProps<V>> {
             value = this.props.value;
         }
 
-        enabled = enabled === undefined || enabled;
+        enabled = enabled ? true : false;
```
Comment (AlexGilleran) [inline magda-web-client/src/Components/Editing/ToggleEditor.tsx]: Tbh I think there's a few fundamental problems with how this was done originally.

1. That "enabled" isn't a great prop name (the field is "enabled" no matter what, what enabled actually does is toggle whether it can be edited.
2. That it allows for the prop to not be set.

How do you feel about renaming `enabled` to `editable` and making it mandatory (i.e. it always has to be set to `true` or `false`) so that this mistake is harder to make?

Comment (t83714) [reply magda-web-client/src/Components/Editing/ToggleEditor.tsx]: Yeah~ I probably can rename it and make it throw an exception if its value is not a boolean~

**Comment by t83714** [comment]
@AlexGilleran  
I have renamed the prop name and it's ready to have another look~
