### PR TITLE
Issue/1916 Fixed: Error messages are not associated with their form fields on suggest dataset form

### LINKED ISSUE #1916: Error messages are not associated with their form fields (high)
### Problem description
The error messages displayed when a form is sent with incomplete or incorrectly completed fields are not programmatically associated with the fields that generated the error.

### Problem reproduction steps
Use the aria-describedby attribute to associate the error message with the form field.
Code sample:
```html
<form class="correspondence-form" method="post">
<h1>Suggest a Dataset</h1>
<label for="message" class="field-label">What sort of data are you looking for?</label>
<textarea class="au-text-input correspondence-message-input au-text-input--invalid" id="message" placeholder="It helps if you're really specific on the kind of data you're looking for and what you would use it for. Feel free to report any problems you run into as well."></textarea>
<label class="correspondence-field-error" aria-describedby="message">Please enter a valid message</label>
```

### Screenshot / Design / File reference
[33] Error messages are not associated with their form fields
Type: WCAG 2.1 failure
Fails 1.3.1 Info and Relationships - Level A
Location: Form error messages, Suggest a Dataset page
Platform: All
Severity: High
What’s the issue?
The error messages displayed when a form is sent with incomplete or incorrectly completed fields are not programmatically associated with the fields that generated the error.
Why it matters
intopia.digi tal 39
When errors are identified after the form is sent and displayed inline, it’s important to make an explicit association between the error message and the form field available to assistive technology.
Our recommendation
Use the aria-describedby attribute to associate the error message with the form field.
Code sample:
```html
<form class="correspondence-form" method="post">
<h1>Suggest a Dataset</h1>
<label for="message" class="field-label">What sort of data are you looking for?</label>
<textarea class="au-text-input correspondence-message-input au-text-input--invalid" id="message" placeholder="It helps if you're really specific on the kind of data you're looking for and what you would use it for. Feel free to report any problems you run into as well."></textarea> 
<label class="correspondence-field-error" aria-describedby="message">Please enter a valid message</label>
```

### PR DESCRIPTION
**Pull request by t83714**
### What this PR does

Fixes #1916 

Fixed: Error messages are not associated with their form fields on suggest dataset form

The recommendation solution seems not right --- `aria-describedby` should be on input field to have error message label to describe the input field rather than the other way round. 

Tested on mac voiceover mode (turn on using Command + F5)

### Checklist

-   [x] unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

File: magda-web-client/src/Components/RequestDataset/RequestFormTemplate.js [hunk 1]
```diff
@@ -156,9 +156,17 @@ export default class RequestFormTemplate extends React.Component {
...
+                    {...(this.state.messageValid
+                        ? {}
+                        : {
+                              "aria-describedby": "messageFieldDescription"
+                          })}
                 />
                 {!this.state.messageValid && (
-                    <label className="correspondence-field-error">
+                    <label
+                        id="messageFieldDescription"
```
Comment (AlexGilleran) [inline magda-web-client/src/Components/RequestDataset/RequestFormTemplate.js]: Can we call this id="messageFieldError"? I'd say the description is the label ;).

Comment (t83714) [reply magda-web-client/src/Components/RequestDataset/RequestFormTemplate.js]: All field naming have been changed from `xxxxDescription` to `xxxxError`~
Please have a look and let me know if anything else requires changes~
