### PR TITLE
Distribution pages: prepend file-specific icon to title. Fixes #1903

### LINKED ISSUE #1903: Distribution pages: prepend file-specific icon to title
### Problem description
Currently we prepend a generic 'tabular' icon to distribution page titles. These icons should be specific to the file/API in questions eg. an geospatial file should be prepended with a geospatial icon

### Problem reproduction steps
1. Go to any distribution page
2. Note the generic icon prepended to title (note: distributions listed in parent dataset page do have correct icons applied)

### Screenshot / Design / File reference
screen shot 2018-12-04 at 12 25 49 pm

### PR DESCRIPTION
**Pull request by nahidakbar**
### What this PR does

Fixes #1903

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

File: magda-web-client/src/Components/DistributionIcon.tsx [hunk 1]
```diff
@@ -0,0 +1,93 @@
+import defaultFormatIcon from "../assets/format-passive-dark.svg";
```
Comment (AlexGilleran) [inline magda-web-client/src/Components/DistributionIcon.tsx]: The name and extension makes me expect a React component here - could it be called `IconFunctions.ts` or something like that?

**Comment by nahidakbar** [comment]
Ready to be looked at again @AlexGilleran
