### PR TITLE
Change text to state/territory in appropriate places; closes #2537

### LINKED ISSUE #2537: When selecting state, the background text asks to select country
**Describe the bug**
When selecting state, the background text asks to select country

**To Reproduce**

1. Go to '/dataset/add'
2. Move to the next page
3. Scroll down to the section where you select region
4. Select a country
5. See the problem

**Expected behavior**
It should say 'Select a State', not a country.

**Screenshots**
state_country_bug

### PR DESCRIPTION
**Pull request by sajidanower23**
### What this PR does

Fixes #2537 

Changed text to reflect state/territory/country accordingly

### Checklist

-   [x] unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

File: magda-web-client/src/Components/Dataset/Add/SpatialAreaInput/TerritorySelect.tsx [hunk 1]
```diff
@@ -50,8 +50,8 @@ const TerritorySelect: FunctionComponent<PropsType> = props => {
     const { countryRegion } = props;
 
     const placeHolderText = countryRegion
-        ? "Please select country..."
```
Comment (t83714) [inline magda-web-client/src/Components/Dataset/Add/SpatialAreaInput/TerritorySelect.tsx]: @sajidanower23 Good pick-up & Nice job~
The territory dropdown is actually the `Offshore Remote Territories` dropdown.
image
Probably should be `Please select a offshore Remote Territory`?
@alyce Could you please help to give some feedback?

Comment (alyce) [reply magda-web-client/src/Components/Dataset/Add/SpatialAreaInput/TerritorySelect.tsx]: Yes could it say "Please select an Offshore Remote Territory"

Comment (sajidanower23) [reply magda-web-client/src/Components/Dataset/Add/SpatialAreaInput/TerritorySelect.tsx]: Thanks @alyce . Done :+1:
