### PR TITLE
Issue/2475 Map Preview: avoid selecting Esri feature server distribution for preview

### LINKED ISSUE #2475: ArcGIS REST National Map preview doesn't work
**Describe the bug**
ArcGIS REST National Map preview doesn't work in Magda eg. for a vector dataset with a GeoJSON resource collected from ArcGIS Open Data. These URLs do work in National Map directly if you copy an paste.

**To Reproduce**

1. Go to https://data.gov.au/dataset/ds-melbourne-water-80e3acf78d2bf23cdf7c6303036323caf8924882f1b44c03eba85acf301a199b/details?q= or https://data.gov.au/dataset/ds-logan-http%3A%2F%2Fdata-logancity.opendata.arcgis.com%2Fdatasets%2F7f24a54ca34b4a45b9f2d7f98d20ec1b_0/details?q=
2. View console errors

**Expected behavior**
A map appears on National Map UI

***Actual Behaviour ***
image

Loading indicator never disappears and Console error "Preview Map notifcation: 
 The MAGDA dataset does not have a distribution with the ID dist-melbourne-water-6bfc3760102e3e193fbf19487d907e8834f033ba8e2bf574af904a94e9d50421 or it does not have a supported format." 
 Can see an error box with the same message if you click "Open in National Map"

Windows 10, Chrome 76

**Additional context**
https://data.gov.au/api/v0/registry/records/ds-melbourne-water-80e3acf78d2bf23cdf7c6303036323caf8924882f1b44c03eba85acf301a199b?dereference=true&aspect=dcat-dataset-strings&optionalAspect=dcat-distribution-strings&optionalAspect=dataset-distributions&optionalAspect=temporal-coverage&optionalAspect=dataset-publisher&optionalAspect=source&optionalAspect=source-link-status&optionalAspect=dataset-quality-rating

Works via copying the ArcGIS REST API url and adding manually in National Map with the autodetect option https://nationalmap.gov.au/#share=s-unUUic7mhnLjmaglGFmVXIsqelR https://nationalmap.gov.au/#share=s-5D18442aiDM5KrPwPr78NLwHNmu

There may also be a different problem with raster dataset previews https://data.gov.au/dataset/ds-logan-http%3A%2F%2Fdata-logancity.opendata.arcgis.com%2Fdatasets%2Fd0899cc42a314e2a8a4db559405f1b48_0/details?q=logan%20city

### PR DESCRIPTION
**Pull request by t83714**
### What this PR does

Fixes #2475 
ArcGIS REST National Map preview doesn't work
- Reason: those Esri links are feature server links that are disabled in `MagdaCatelogItem`
- Solution: avoid selecting Esri feature server distribution for preview. The preview program will use the next available data source (for most cases will be GeoJson) if available.

Known Issues:
- Some of the GeoJson files are quite large which will cause performance issue in TerriaJs
  - e.g. this one: https://data.gov.au/dataset/ds-melbourne-water-9b6b772591310b15d6c3b5ceaf320af18262acfc8db5828936709b912389b611/details?q=
- We probably should disable GeoJSON preview by file size. However, at this moment, we don't have a reliable way of getting distribution file size.
  - We probably can ask Link Status Minion to record this as it will try to download the actual data file to test the link status. Create a separate ticket [here](https://github.com/magda-io/magda/issues/2535)

### Checklist

-   [x] unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

File: magda-web-client/src/Components/Common/DataPreviewMap.js [hunk 1]
```diff
@@ -18,8 +18,18 @@ export const defaultDataSourcePreference = [
 ];
 
 export const isSupportedFormat = function(format) {
+    const dataSourcePreference = defaultDataSourcePreference.map(
+        preferenceItem => {
+            if (typeof preferenceItem === "string") return preferenceItem;
```
Comment (AlexGilleran) [inline magda-web-client/src/Components/Common/DataPreviewMap.js]: Could we put some `{}`s around this one? Makes it a bit hard to see what's going on :)

File: magda-web-client/src/Components/Common/DataPreviewMap.js [hunk 2]
```diff
@@ -9,7 +9,7 @@ import Spinner from "Components/Common/Spinner";
 
 export const defaultDataSourcePreference = [
     "WMS",
-    "ESRI REST",
+    ["ESRI REST", /MapServer/],
```
Comment (AlexGilleran) [inline magda-web-client/src/Components/Common/DataPreviewMap.js]: Rather than have this as an array of `string | string[]` can we maybe make this an array of `{id: string; urlRegex?: RegExp}` ? I think that makes it a bit more obvious how to add new ones.

File: magda-web-client/src/Components/Common/DataPreviewMap.js (hunk 1 above)
Comment (t83714) [reply magda-web-client/src/Components/Common/DataPreviewMap.js]: Updated~

File: magda-web-client/src/Components/Common/DataPreviewMap.js (hunk 2 above)
Comment (t83714) [reply magda-web-client/src/Components/Common/DataPreviewMap.js]: Updated~

**Comment by t83714** [comment]
@AlexGilleran 
Updated the code according to your feedback~
I think it's ready to have another look~
